openapi: "3.0.0"

info:
  title: "APIs ServiEstado"
  version: "1.0.0"
  description: "Documentación relacionada a las APIs utilizadas para el nuevo Portal Empresa de ServiEstado."


servers:
  - url: http://localhost:3000/ms/se-ms-registrobiller/v1


tags:
- name: "registro-biller"
- name: "login"
paths:
  /registro-biller:
    post:
      tags:
      - "registro-biller"
      summary: "Registra a un nuevo BIller"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/registroBiller"
      responses:
        200:
          description: "Datos Correctos"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseCorrectData"
        400:
          description: "Datos incompletos"
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ApiResponseIncorrectData"
  /login:
    post:
      tags:
      - "login"
      summary: "Da acceso a un usuario BIller"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/login"
      responses:
        200:
          description: "Datos Correctos"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseCorrectData"
        400:
          description: "Usuario no encontrado"
          content:
            application/json:    
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ApiResponseIncorrectData"
                  - $ref: "#/components/schemas/ApiResponseUserNotFound"
  /login/cambio-contrasenia:
    put:
      tags:
      - "login"
      summary: "Cambia clave a un usuario BIller"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/changePassword"
      responses:
        200:
          description: "Datos Correctos"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseCorrectData"
        400:
          description: "Datos incompletos"
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ApiResponseIncorrectData"
components:
  schemas:
  
    registroBiller:
      type: "object"
      properties:
        business_name:
          type: "string"
          example: "businessname"
        rut:
          type: "string"
          example: "rut"
        name:
          type: "string"
          example: "name"
        last_name:
          type: "string"
          example: "last_name"
        email:
          type: "string"
          example: "email@gmail.com"
        phone:
          type: "string"
          example: "963214569"
        position:
          type: "string"
          example: "position"
    login:
      type: "object"
      properties:
        rut:
          type: "string"
          example: "11111111-2"
        email:
          type: "string"
          example: "entel@cliente.cl"
        password:
          type: "string"
          example: "12345678"
        changePassword:
          type: "boolean"
          example: false
    changePassword:
      type: "object"
      properties:
        rut:
          type: "string"
          example: "11111111-1"
        email:
          type: "string"
          example: "cliente@cliente.cl"
        oldPassword:
          type: "string"
          example: "RC123456"
        newPassword:
          type: "string"
          example: "12345678"
    ApiResponseCorrectData:
      type: "object"
      properties:
        code:
          type: "string"
          example: "OK.000"
        message:
          type: "string"
          example: "Datos Correctos"
        data:
          type: "object"
          example: {}
    ApiResponseIncorrectData:
      type: "object"
      properties:
        code:
          type: "string"
          example: "ERROR.001"
        message:
          type: "string"
          example: "Datos Incorrectos"
        data:
          type: "object"
          example: {}
    ApiResponseIncompleteData:
      type: "object"
      properties:
        code:
          type: "string"
          example: "ERROR.001"
        message:
          type: "string"
          example: "Datos Incompletos"
        data:
          type: "object"
          example: {}
    ApiResponseUserNotFound:
      type: "object"
      properties:
        code:
          type: "string"
          example: "ERROR.001"
        message:
          type: "string"
          example: "Usuario no encontrado"
        data:
          type: "object"
          example: {}