openapi: "3.0.0"

info:
  title: "APIs ServiEstado"
  version: "1.0.0"
  description: "Documentación relacionada a las APIs utilizadas para el nuevo Portal Empresa de ServiEstado."


servers:
  - url: http://localhost:3000/ms/se-ms-registrobiller/v1


tags:
- name: registro-biller
- name: login
- name: maintainer-user
paths:
  /registro-biller:
    post:
      tags:
      - registro-biller
      summary: Registra a un nuevo BIller
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registroBiller'
      responses:
        200:
          description: Datos Correctos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseCorrectData'
        400:
          description: Datos Incorrectos
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/ApiResponseIncorrectData'
  /maintainer-user/registerNewUser:
    post:
      tags:
      - maintainer-user
      summary: Registra a un nuevo usuario
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registerNewUser'
      responses:
        200:
          description: Datos Correctos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseCorrectData'
        400:
          description: Datos Incorrectos
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/ApiResponseIncorrectData'
  /login:
    post:
      tags:
      - login
      summary: Da acceso a un usuario BIller
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login'
      responses:
        200:
          description: Datos Correctos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseCorrectData'
        400:
          description: Datos Incorrectos
          content:
            application/json:    
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ApiResponseIncorrectData'
                  - $ref: '#/components/schemas/ApiResponseIncorrectPasswrd'
                  - $ref: '#/components/schemas/ApiResponsekeyLocked'
  /login/cambio-contrasenia:
    put:
      tags:
      - login
      summary: Cambia clave a un usuario BIller
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/changePassword'
      responses:
        200:
          description: Datos Correctos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseCorrectData'
        400:
          description: Datos Incorrectos
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/ApiResponseIncorrectData'
components:
  schemas:
    registroBiller:
      type: object
      properties:
        business_name:
          type: string
          example: EMPRESA NACIONAL DE TELECOMUNICACIONES S.A.
        rut:
          type: string
          example: 92580000-7
        name:
          type: string
          example: José
        last_name:
          type: string
          example: Gonzalez Muñoz
        email:
          type: string
          example: entel@cliente.cl
        phone:
          type: string
          example: 223600123
        position:
          type: string
          example: Gerente
    login:
      type: object
      properties:
        rut:
          type: string
          example: 76124890-1
        email:
          type: string
          example: claudio.monasterio@telefonica.com
        password:
          type: string
          example: movistar
        changePassword:
          type: boolean
          example: false
    changePassword:
      type: object
      properties:
        rut:
          type: string
          example: 92580000-7
        email:
          type: string
          example: entel@cliente.cl
        oldPassword:
          type: string
          example: entel123
        newPassword:
          type: string
          example: entel321
    registerNewUser:
      type: object
      properties:
        name:
          type: string
          example: Juan Perez
        email:
          type: string
          example: entel@cliente.cl
        perfil:
          type: string
          example: Administrador
        asignarContacto:
          type: boolean
          example: true
        tipoContacto:
          type: string
          example: Contacto Operacional
    ApiResponseCorrectData:
      type: object
      properties:
        code:
          type: string
          example: OK.000
        message:
          type: string
          example: Datos Correctos
        data:
          type: object
          example: {}
    ApiResponseIncorrectData:
      type: object
      properties:
        code:
          type: string
          example: ERROR.001
        message:
          type: string
          example: Datos Incorrectos
        data:
          type: object
          example: {}
    ApiResponseIncompleteData:
      type: object
      properties:
        code:
          type: string
          example: ERROR.001
        message:
          type: string
          example: Datos Incompletos
        data:
          type: object
          example: {}
    ApiResponseIncorrectPasswrd:
      type: object
      properties:
        code:
          type: string
          example: ERROR.001
        message:
          type: string
          example: Clave incorrecta
        data:
          type: object
          example: {}
    ApiResponsekeyLocked:
      type: object
      properties:
        code:
          type: string
          example: ERROR.001
        message:
          type: string
          example: Clave Bloqueada. Puedes recuperarla presionando el link “¿olvidaste tu contraseña?
        data:
          type: object
          example: {}
    